name: fedmps_modified
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.24.1
  - scikit-learn=1.2.0
  - tqdm=4.64.1
  # PyTorch 核心组件 (含 CUDA 11.7 支持)
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - pip:
    - pandas
    - matplotlib
    - tensorboardX